### PR TITLE
Updated section about writing titles

### PR DESCRIPTION
**Pull request by julian-cable**
@daobrien @sffrench Please review the "Writing Effective Titles" section, which I've updated to reflect the recently changed guidance that Pat announced.

### CODE REVIEW

**Review by daobrien — COMMENTED** [review]
My initial reaction to this is that it's very focused on our course designs and requirements. The Style Guide is broader than that. Note also that I would hesitate to update id's unless absolutely necessary. Whenever you update an id, any links to that section will break. The parts about omitting "Describing", etc., are fine; just remember the overall audience is not RHT, but rather anyone writing technical documentation.

**Comment by julian-cable** [comment]
I have reverted the ID of that title. 
@daobrien What other guidance about titles would you specifically suggest to cover? 
My aim in this PR is to communicate (and publish soon) the changed RHT guidance about writing titles, which Pat has asked for. 
If there is also a need to widen the scope significantly, then I would suggest having a new issue for it.

**Comment by daobrien** [comment]
> I have reverted the ID of that title. @daobrien What other guidance about titles would you specifically suggest to cover? My aim in this PR is to communicate (and publish soon) the changed RHT guidance about writing titles, which Pat has asked for. If there is also a need to widen the scope significantly, then I would suggest having a new issue for it.

It's not about "other" guidance, or widening the scope; in fact, quite the opposite. The way we're going atm we're reducing the scope, and focusing primarily on our course requirements, which is not what the RH Technical Writing Style Guide is about.

Consider this:
'Activities and subtasks that the student should perform can alternatively use an imperative verb for clarity. Imperative verbs are prescriptive, such as "Create" or "Delete". Example: “Assess the Health of an OpenShift Cluster”.'

This is 100% about students taking a course. It might be useful if you're writing a subsection about procedures or similar, but in general it's too restrictive for my liking. Note also that there seem to be quite a few cases of smart quotes in this PR; where did they come from?

We also need to be careful with our terminology. E.g., in "Configuring OpenShift" or whatever, "configuring" is not a gerund; it's a verb. Gerunds are nouns, or more specifically, a verb form which _functions_ as a noun. It's often easier to just use examples of what works and what doesn't.

**Comment by sffrench** [comment]
If the purpose is go to add Pars changes then this looks good to me. But for future David's concerns are something we need to think about.

**Review by sffrench — APPROVED** [review]

**Comment by daobrien** [comment]
tbh I disagree with merging this as-is, but I'm only one person. We need more eyes.

**Comment by julian-cable** [comment]
I have made further edits. In an attempt to make the guidance more generic, I changed "student" to "user". For the one paragraph that is specific to training, I added an introductory statement to that effect. I have removed the smart quotes (which were probably from content that was pasted from a presentation). 
@daobrien What do you think now?

**Review by daobrien — APPROVED** [review]
You might be able to get some graphene between this and ideal, but you'd struggle. Go for it.

**Pull request merged**
