### PR TITLE
Jcable/291 diag label

### PR DESCRIPTION
**Pull request by julian-cable**

### CODE REVIEW

**Comment by julian-cable** [comment]
#285 and #297 should not be part of this PR.

**Comment by daobrien** [comment]
I started looking at this and then thought... I've already reviewed some of this. What happened to that review?
@julian-cable

**Comment by julian-cable** [comment]
In the linked https://github.com/StyleGuides/WritingStyleGuide/issues/291 issue?

**Comment by julian-cable** [comment]
Closing PR because incorrect commits were included.

**Pull request closed without merging**
